---
- name: install build dependencies
  become: yes
  become_user: root
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
    cache_valid_time: 604800
  with_items:
    - libxcb-randr0-dev

### tmpdir shenanigans
- name: create a temp directory
  command: mktemp -d -p /tmp ansible.XXXX
  register: tmpdir_mktemp
  when: tmpdir_path is undefined

- name: set tmpdir_path
  set_fact:
    tmpdir_path: "{{ tmpdir_mktemp.stdout }}"
  when: tmpdir_path is undefined
### end tmpdir shenanigans

- name: create working directories
  file:
    path: "{{ ansible_env.HOME }}/{{item}}"
    state: directory
  with_items:
    - bin

# TODO: ensure bin is in the path? how sophisticated can this get

- name: clone inversion repository
  git:
    repo: git://github.com/ericcrosson/xrandr-invert-colors
    dest: "{{ tmpdir_path }}/xrandr-invert-colors"

- name: make inversion binary
  make:
    chdir: "{{ tmpdir_path }}/xrandr-invert-colors"
    params:
      NUM_THREADS: 4

- name: install inversion binary
  become: yes
  become_user: root
  make:
    chdir: "{{ tmpdir_path }}/xrandr-invert-colors"
    target: install

- name: cleanup workspace directory
  file:
    path: "{{ tmpdir_path }}/xrandr-invert-colors"
    state: absent
